import json, sys
sys.stdout.reconfigure(encoding='utf-8')

with open('universal-research-system/state.json', 'r', encoding='utf-8') as f:
    state = json.load(f)

validated = [
  {'from':'Indican','to':'Urinary Bile Acids','type':'causal','explanation':'Protein maldigestion-driven dysbiosis generates excess indole requiring hepatic conjugation; the indole toxin load congests the liver, impairing first-pass bile acid clearance and producing UBA spillover into urine.','evidence_count':2},
  {'from':'Indican','to':'8-OHdG','type':'causal','explanation':'Chronic dysbiosis signaled by Indican drives 8-OHdG elevation through two converging ROS pathways: pathogen-triggered neutrophil oxidative burst and hepatic CYP450 ROS generation during Phase I indole detoxification.','evidence_count':2},
  {'from':'Indican','to':'Zonulin','type':'causal','explanation':'SIBO (the primary condition producing elevated Indican) constitutes the bacterial small intestinal colonization that is Zonulin\'s primary physiological trigger, directly causing TJ disassembly and intestinal hyperpermeability.','evidence_count':2},
  {'from':'Indican','to':'Histamine \u2014 MBA','type':'architectural','explanation':'SIBO/dysbiosis is the shared upstream structural condition driving both: tryptophanase bacteria produce indole (Indican) while histamine-decarboxylase bacteria simultaneously produce excess histamine, making both markers co-indicators of the same dysbiotic ecology.','evidence_count':2},
  {'from':'Indican','to':'DAO (Diamine Oxidase)','type':'causal','explanation':'Dysbiosis and leaky gut (signaled by Indican) destroy intestinal mucosal crypt epithelial cells, the exclusive production site of DAO; Indican elevation is mechanistically linked to mucosal architecture destruction that reduces DAO output, confirmed by the correlation between serum DAO and intestinal permeability.','evidence_count':2},
  {'from':'Indican','to':'Systemic Oxidative Stress Cascade','type':'causal','explanation':'Gut dysbiosis evidenced by Indican drives systemic ROS production through immune-mediated oxidative burst from pathogen load and through hepatic CYP450 ROS generation during Phase I processing of indole-derived xenobiotics.','evidence_count':2},
  {'from':'Indican','to':'Hepatic Detoxification Impairment','type':'causal','explanation':'Indole is a direct Phase II hepatic conjugation substrate; excess indole from dysbiosis constitutes an ongoing hepatic toxic load, and high-to-very-high Indican explicitly indicates liver dysfunction in FDN, directly contributing to Phase I/II processing impairment.','evidence_count':2},
  {'from':'Indican','to':'Histamine-DAO Regulatory System','type':'causal','explanation':'SIBO/dysbiosis (Indican) destabilizes the Histamine-DAO regulatory balance through two simultaneous mechanisms: histamine-producing SIBO bacteria increase production while dysbiosis-driven mucosal crypt destruction reduces DAO degradation capacity, creating a double-hit on the regulatory equilibrium.','evidence_count':2},
  {'from':'Indican','to':'Secretory IgA \u2014 SHP','type':'architectural','explanation':'Gut dysbiosis (Indican) chronically activates the HPA axis via the gut-brain axis, elevating cortisol, which directly suppresses sIgA production (the primary mechanism of sIgA SHP depletion); both variables are components of the gut-HPA-immune axis.','evidence_count':2},
  {'from':'Indican','to':'HPA Axis Dysregulation Pattern','type':'causal','explanation':'Gut dysbiosis (Indican) generates pro-inflammatory cytokines and LPS that traverse the gut-brain-HPA axis to activate CRH/ACTH/cortisol signaling; FDN explicitly states protein maldigestion causes hormone imbalance, and GI dysbiosis is a named chronic stressor driving HPA dysregulation.','evidence_count':2},
  {'from':'Indican','to':'Pregnenolone Steal and Steroidogenesis Disruption','type':'architectural','explanation':'Gut dysbiosis (Indican) drives HPA axis dysfunction, and HPA dysfunction drives steroidogenesis disruption by shifting adrenal production toward cortisol and away from DHEA/sex hormones; FDN explicitly states protein maldigestion causes hormone imbalance; both are components of the stress-hormone-metabolic chaos axis.','evidence_count':2},
  {'from':'Indican','to':'Cortisol \u2014 Diurnal Pattern','type':'causal','explanation':'Chronic gut dysbiosis (Indican) constitutes a persistent physiological stressor that activates HPA signaling, disrupting the cortisol diurnal pattern; FDN identifies gut pathogen load as a primary chronic stressor driving cortisol phase transitions.','evidence_count':2},
  {'from':'Indican','to':'DHEA-S','type':'causal','explanation':'Dysbiosis (Indican) drives HPA activation and chronic cortisol elevation; elevated cortisol reciprocally suppresses DHEA-S production in the zona reticularis, shifting the adrenal axis toward catabolic dominance.','evidence_count':2},
  {'from':'Indican','to':'Cortisol-to-DHEA Ratio','type':'causal','explanation':'Gut dysbiosis (Indican) drives both cortisol elevation (HPA activation) and DHEA-S suppression (reciprocal cortisol-DHEA relationship), directly shifting the cortisol:DHEA ratio toward catabolic dominance; Indican research explicitly states adverse hormone imbalance as a consequence.','evidence_count':2},
  {'from':'Indican','to':'Estradiol','type':'architectural','explanation':'Dysbiosis (Indican) elevates Estradiol through two independent mechanisms: (1) dysbiotic bacteria produce beta-glucuronidase which deconjugates and reactivates excreted estrogens entering circulation; (2) SIBO-driven histamine production directly stimulates ovarian estradiol synthesis.','evidence_count':2},
  {'from':'Indican','to':'Progesterone','type':'causal','explanation':'Gut dysbiosis (Indican) activates HPA, elevating cortisol, which suppresses progesterone production through adrenal precursor competition and central negative feedback on the HPG axis; FDN identifies HPA-driven cortisol dominance as the primary mechanism of progesterone insufficiency.','evidence_count':2},
  {'from':'Indican','to':'Testosterone','type':'causal','explanation':'Gut dysbiosis (Indican) drives cortisol dominance via HPA activation; elevated cortisol suppresses testosterone through reduced DHEA substrate availability, HPG axis suppression, and increased aromatase activity.','evidence_count':2},
  {'from':'Indican','to':'Melatonin','type':'causal','explanation':'Gut dysbiosis and mucosal damage (both signaled by Indican) impair enterochromaffin cell function; the SHP melatonin marker specifically measures GI EC cell output (which produces 400x more melatonin than the pineal gland), making Indican-driven mucosal damage a direct cause of reduced noon melatonin.','evidence_count':2},
  {'from':'Indican','to':'Dysbiosis-Intestinal Permeability Feedback Loop','type':'architectural','explanation':'Indican is the urinary metabolite marker of the same dysbiosis that drives the Dysbiosis-Intestinal Permeability Feedback Loop; elevated Indican directly signals the LPS-producing bacterial overgrowth that initiates TJ compromise and the self-amplifying dysbiosis-permeability cycle.','evidence_count':2},
  {'from':'Indican','to':'Mucosal Immune Tolerance and sIgA Function','type':'causal','explanation':'Chronic dysbiosis (Indican) continuously deploys sIgA to neutralize dysbiotic organisms and translocated antigens; the SIBO, dysbiosis, and leaky gut generating elevated Indican progressively exhaust mucosal sIgA reserves, eroding mucosal immune tolerance.','evidence_count':2},
  {'from':'Indican','to':'Gut-Brain-HPA Bidirectional Axis','type':'architectural','explanation':'Indican-signaled gut dysbiosis IS the GI component activating the gut-to-HPA direction of the bidirectional axis; the dysbiotic LPS, pro-inflammatory cytokines, and microbial metabolites generated by Indican-confirmed dysbiosis are the molecular signals traversing the gut-brain-HPA pathway.','evidence_count':2},
  {'from':'Indican','to':'Reactive Food Burden \u2014 MRT','type':'causal','explanation':'Protein maldigestion and leaky gut (both signaled by Indican) allow partially digested food antigens to translocate systemically, creating the conditions for immune sensitization measurable by MRT; hypochlorhydria (indicated by high-to-very-high Indican) specifically leaves intact food proteins available as antigens.','evidence_count':2},
  {'from':'Indican','to':'H. pylori','type':'architectural','explanation':'H. pylori causes hypochlorhydria through urease-mediated HCl neutralization; high-to-very-high Indican specifically indicates hypochlorhydria as an upstream cause; H. pylori is the upstream causal driver and elevated Indican is a downstream consequence, sharing hypochlorhydria as the structural node connecting them.','evidence_count':2},
  {'from':'Indican','to':'Candida and Fungal Overgrowth','type':'architectural','explanation':'FDN Module 4 explicitly states elevated Indican points toward fungal overgrowth; Candida and the bacteria producing indole (generating Indican) co-occupy the same dysbiotic ecological niche and are co-occurring components of the same GI microbial imbalance.','evidence_count':2},
  {'from':'Indican','to':'Parasitic Load','type':'architectural','explanation':'The dysbiotic, hypochlorhydric, mucosal-compromised GI environment signaled by Indican creates the ecological conditions for parasitic colonization; insufficient gastric acid (indicated by high Indican) reduces the protective barrier against ingested parasites.','evidence_count':2},
  {'from':'Indican','to':'Dysbiotic and Opportunistic Bacteria','type':'causal','explanation':'Dysbiotic anaerobic bacteria with tryptophanase activity ARE the direct mechanism generating urinary Indican; elevated Indican is the specific metabolic output of these organisms acting on undigested tryptophan, making this a direct causal relationship.','evidence_count':2},
  {'from':'Indican','to':'Commensal Flora Balance','type':'causal','explanation':'Loss of commensal flora balance allows dysbiotic anaerobes to expand and generate tryptophanase-driven Indican elevation; reciprocally, elevated Indican signals the disrupted commensal balance that allows these organisms to dominate.','evidence_count':2},
  {'from':'Indican','to':'Calprotectin and Lactoferrin','type':'architectural','explanation':'Gut dysbiosis (Indican) generates mucosal inflammation via LPS, bacterial products, and immune activation; calprotectin is released by neutrophils recruited to this dysbiosis-driven mucosal inflammation, making both co-markers of the same GI inflammatory state.','evidence_count':2},
  {'from':'Indican','to':'Beta-glucuronidase','type':'architectural','explanation':'Both Indican and beta-glucuronidase are parallel metabolic outputs of the same dysbiotic bacterial populations: Indican from anaerobic tryptophanase activity and B-GUS from dysbiotic glucuronidase activity; co-elevation of both markers indicates the same underlying dysbiotic ecology.','evidence_count':2},
  {'from':'Indican','to':'Anti-gliadin IgA','type':'causal','explanation':'Hypochlorhydria and protein maldigestion (Indican) leave intact gliadin peptides available; leaky gut (Indican) allows these to translocate systemically, triggering the mucosal anti-gliadin IgA immune response.','evidence_count':2},
  {'from':'Indican','to':'Secretory IgA \u2014 GI tract','type':'causal','explanation':'Chronic dysbiosis (Indican) continuously challenges GI sIgA production through ongoing microbial antigen burden; the same SIBO and dysbiotic overgrowth generating elevated Indican depletes and dysregulates the sIgA first-line mucosal defense.','evidence_count':2},
  {'from':'Urinary Bile Acids','to':'8-OHdG','type':'causal','explanation':'Hepatic dysfunction (elevated UBAs) impairs detoxification capacity, increasing CYP450-generated ROS during Phase I processing; bile acid recirculation also brings pro-oxidant toxins and xenobiotics back into hepatocytes, both driving 8-OHdG-generating oxidative DNA damage.','evidence_count':2},
  {'from':'Urinary Bile Acids','to':'Zonulin','type':'causal','explanation':'Poor bile flow (very low UBAs) removes bile acids antimicrobial function in the small intestine, enabling bacterial overgrowth which is Zonulin\'s primary physiological trigger; bile acids also regulate epithelial TJ protein expression via FXR receptors, making bile flow disruption a direct structural cause of permeability changes.','evidence_count':2},
  {'from':'Urinary Bile Acids','to':'Histamine \u2014 MBA','type':'architectural','explanation':'SIBO/dysbiosis is the shared upstream structural condition: SIBO bacteria produce histamine (driving Histamine MBA elevation) while also disrupting normal enterohepatic bile recycling (driving UBA abnormalities); both are co-markers of the SIBO/dysbiosis complex.','evidence_count':2},
  {'from':'Urinary Bile Acids','to':'DAO (Diamine Oxidase)','type':'architectural','explanation':'Both UBAs and DAO are co-depleted in the same structural disease states (IBD, Crohn\'s, UC): low UBAs indicate poor bile flow and IBD-related enterohepatic dysfunction while very low DAO reflects crypt cell destruction in these same conditions, making both co-markers of intestinal mucosal disease severity.','evidence_count':2},
]

discarded = [
  {'from':'Indican','to':'Occult Blood','reason':'Evidence for a direct causal link between dysbiosis (Indican) and mucosal bleeding (Occult Blood) does not reach Relevant confidence (60+); elevated Indican indicates severe dysbiosis but does not specifically predict structural GI lesions causing mucosal bleeding; occult blood reflects distinct structural pathology beyond general dysbiotic mucosal irritation.'},
]

state['connections']['validated'].extend(validated)
state['connections']['discarded'].extend(discarded)
state['connections']['pending'] = state['connections']['pending'][36:]
state['last_updated'] = '2026-03-24T08:00:00Z'

with open('universal-research-system/state.json', 'w', encoding='utf-8') as f:
    json.dump(state, f, indent=2, ensure_ascii=False)

print(f'Written: {len(validated)} validated, {len(discarded)} discarded')
print(f'Pending remaining: {len(state["connections"]["pending"])}')
